### ISSUE TITLE
New instance

### ISSUE THREAD

**Issue by RealFascinated** [realaravinth/libmedium#13]
Url: https://libmedium.fascinated.cc
Country: Germany
Protection: Cloudflare

**Comment by realaravinth** [comment]
thanks, will add it to the list :)

**Comment by realaravinth** [comment]
[This commit](https://github.com/realaravinth/libmedium/commit/5770f93fb8fb7c0866d4bf6b4150d7e917e849a9) lists the instance mentioned above. Closing :)
