### ISSUE TITLE
Font rendering on Firefox

### ISSUE THREAD

**Issue by shvchk** [realaravinth/libmedium#24]
[Example article](https://libmedium.batsense.net/@tylerneely/fear-and-loathing-in-lock-free-programming-7158b1cdd50c)
![image](https://github.com/realaravinth/libmedium/assets/872945/8469ccdc-d408-4d21-b376-d66699b3e1e3)

Firefox 116.0.3, clean profile

UPD: probably my local configuration issue, closing for now

**Comment by realaravinth** [comment]
The styling on this thing was an afterthought, I wouldn't be surprised if I messed something up 😅
