### ISSUE TITLE
ARM64 docker image support

### ISSUE THREAD

**Issue by FireMasterK** [realaravinth/libmedium#30]
I was looking to host a public instance, but I realized there's no arm64 support.

I looked at the CI configuration for a bit, and it looks like support can be added by using https://woodpecker-ci.org/plugins/Docker%20Buildx. I'd be happy to submit a PR, but I'm not sure how multi-architecture support works in this. (Does qemu need to be installed on your CI?)

**Comment by realaravinth** [comment]
I haven't tried using buildx with woodpecker. I remember compiling multiarch with buildx locally requiring some work initially, but that was a long time ago. I don't know what it's like on buildx land :)

I'd love the PR, but it might be annoying for the first time around. So would like to take a crack at it, if you don't mind :)

**Comment by FireMasterK** [comment]
Hello, any updates on this? If not, should I take a stab at sending a PR? I'm just afraid that you might need to first manually configure buildx, qemu or similar on your CI for it to work.

**Comment by realaravinth** [comment]
Hey, sorry it took so long. I managed to configure buildx for multiarch builds, but had trouble [using it from within Woodpecker](https://ci.batsense.net/repos/84/pipeline/20/4). Took a fresh stab at it today, got it working. [ARM64 images are now available on docker hub](https://hub.docker.com/r/realaravinth/libmedium/tags).

**Comment by jollySleeper** [comment]
Hi @realaravinth can't see ARM64 Images on DockerHub.
Any issue faced?

**Comment by realaravinth** [comment]
Hi @jollySleeper,
The CI was supposed to build and publish images, but it looks like it failed for some reason ([logs lack information](https://ci.batsense.net/repos/84/pipeline/40/4)). I re-ran the CI job and it seems to work now.

**Comment by jollySleeper** [comment]
Thank You So Much @realaravinth
