### ISSUE TITLE
[Bug] Line permalinking not working with multiple code blocks in article

### ISSUE THREAD

**Issue by KaKi87** [realaravinth/libmedium#32]
Hi,

Permalinking to a line of the 2nd+ code snippet of a page links to a line of the 1st code snippet of the page.

Thanks

**Comment by realaravinth** [comment]
Hello o/

Thanks for filing this issue! [This PR](https://git.batsense.net/realaravinth/libmedium/pulls/11) uses unique IDs for permanent links, which should fix this issue. I'll ping once it's merged and published on GitHub too.

**Comment by KaKi87** [comment]
Very well, thanks !

Would you rather that I had submitted the issue on your Forgejo instance ?

If so, I'd like to suggest changing the homepage *Source Code* link (next to the *Demo Article* one).

**Comment by realaravinth** [comment]
The long term goal is to switch to my Forgejo instance, but I don't mind receiving issues on GH also.

> If so, I'd like to suggest changing the homepage Source Code link (next to the Demo Article one).

That's actually a very good idea, thanks!
