### ISSUE TITLE
Vulnerabilities in libmedium crates

### ISSUE THREAD

**Issue by F3llFr0mTh3Sky** [realaravinth/libmedium#34]
calico@tux ~/Dépôts/realavarinth/libmedium $ 
cargo ebuild
Error: Found 3 vulnerabilities:

Crate:    h2
Version:  0.3.21
Title:    Resource exhaustion vulnerability in h2 may lead to Denial of Service (DoS)
Date:     2024-01-17
ID:       RUSTSEC-2024-0003
URL:      https://rustsec.org/advisories/RUSTSEC-2024-0003
Solution: Upgrade to ^0.3.24 or >=0.4.2

Crate:    h2
Version:  0.3.21
Title:    Degradation of service in h2 servers with CONTINUATION Flood
Date:     2024-04-03
ID:       RUSTSEC-2024-0332
URL:      https://rustsec.org/advisories/RUSTSEC-2024-0332
Solution: Upgrade to ^0.3.26 or >=0.4.4

Crate:    mio
Version:  0.8.8
Title:    Tokens for named pipes may be delivered after deregistration
Date:     2024-03-04
ID:       RUSTSEC-2024-0019
URL:      https://rustsec.org/advisories/RUSTSEC-2024-0019
Solution: Upgrade to >=0.8.11

**Comment by realaravinth** [comment]
Thanks for the heads-up! o/

I installed [renovate bot](https://renovatebot.com) to ease maintenance. [Almost all the dependencies are updated.](https://git.batsense.net/realaravinth/libmedium/compare/16a6044773ff7f3972f8385c21a63f676348a556...master)
