### ISSUE TITLE
[Bug] Partly unreadable article & evaluated HTML code

### ISSUE THREAD

**Issue by KaKi87** [realaravinth/libmedium#36]
Hi,

When browsing the following article : https://libmedium.batsense.net/@wezzcoetzee/the-beth-stack-c5887a606ed3

The beginning of the article can't be read, and it seems related to viewport width :

![](https://github.com/realaravinth/libmedium/assets/21284089/ef2d9b78-20d0-44b7-9141-8bf3a58651db)

And HTML in code blocks gets evaluated :

![](https://github.com/realaravinth/libmedium/assets/21284089/1cfb6e2f-24eb-4960-aa3a-c62491027316)
![](https://github.com/realaravinth/libmedium/assets/21284089/f5d117a7-45f5-4f36-a0c5-551c1b434677)

Also, I was going to submit the issue at git.batsense.get as per our previous discussion, but registrations are closed :sweat_smile: 

Thanks

**Comment by realaravinth** [comment]
Thanks for creating this issue, I'll take a look at it over the weekend o/

Regarding git.batsense.net: sorry about that, I had a spammer creating accounts right after I delete them. It's re-opened now :)

**Comment by KaKi87** [comment]
Ah yes, the whole Forgejo community is struggling with spam. Personally, as I'm getting out of options, I'm thinking about integrating Akismet to it :sweat_smile:

**Comment by realaravinth** [comment]
It will be cool if we could build a FOSS alternative for Akismet :sweat_smile: 

aside: [the fix was simple](https://git.batsense.net/realaravinth/libmedium/pulls/37), it should be deployed in an hour :)

**Comment by KaKi87** [comment]
What about the secon issue though ?

**Comment by realaravinth** [comment]
My apologies, I overlooked it. Will fix it ASAP.
